### ISSUE TITLE
启用配置文件后，config.cookie的配置有问题，可以更正

### ISSUE THREAD

**Issue by brave688** [SweetInk/wqxuetang-pdf-downloader#10]
启用配置文件后，明明已经登录还是显示未登录，用前一版本没有问题，看了一下，应该在config.cookie的值前面插入“PHPSESSID="，即”config.cookie=PHPSESSID=123456“ ，虽然很怪，但是不用改代码了。另外现在可能系统压力太大了，基本爬不动，下载下来也是有问题的图像。
![image](https://user-images.githubusercontent.com/20045733/73969579-a277d980-4956-11ea-890f-44ae944d57bb.png)

**Comment by SweetInk** [comment]
`Cookie`的值现在就是复制登录成功后，`Cookie`头后面的所有内容.因为页面偶尔还会出现阿里云的滑块验证，所以需要人工过验证后，cookie项不单单只需要`PHPSESSIONID`

**Comment by brave688** [comment]
没有仔细看read.me的截图，自作聪明，本问题了结。
