### ISSUE TITLE
大概能下 70 来页，随后要等大概 1 个多小时

### ISSUE THREAD

**Issue by meininghang** [SweetInk/wqxuetang-pdf-downloader#11]
如题，每次能下 70 页，然后就要等待，在此期间，进行的诸如重新登录等操作是不行的，反正也够用了。

**Comment by Becods** [comment]
问题重复[issues9](https://github.com/SweetInk/wqxuetang-pdf-downloader/issues/9)

**Comment by SweetInk** [comment]
服务器对同一用户连续请求书籍图片做了限流，目前不知道如何处理，可以尝试调整`config.properties`中`defaultSleepTime`,来降低对服务器的请求频率

**Comment by meininghang** [comment]
谢谢，问题已经解决，将config.defaultSleepTime=1000改为 3600 后已经可以完整运行。
