### ISSUE TITLE
软件失效了，不能下载了

### ISSUE THREAD

**Issue by lovexuanqi521** [SweetInk/wqxuetang-pdf-downloader#14]

**Comment by AutoBrain** [comment]
一直http error code 500，浏览器可以正常访问

**Comment by xinpo66** [comment]
我的也是

**Comment by lovexuanqi521** [comment]
@AutoBrain 浏览器能下载吗？

**Comment by 66508393** [comment]
网站更新了！失效了！

**Comment by AutoBrain** [comment]
> @AutoBrain 浏览器能下载吗？

浏览器直接拉可以把图片拉下来

**Comment by EveryStepOneClimb** [comment]
我的提示未登录，今天更新了。另一个脚本也挂了。等大神研究

**Comment by SweetInk** [comment]
**分析中...** 😂

**Comment by qs9515** [comment]
https://lib-nuanxin.wqxuetang.com/page/img/
这个地址改成了
https://lib-nuanxin.wqxuetang.com/page/lmg/
，可能Jwt的算法也有调整吧。

**Comment by SweetInk** [comment]
> https://lib-nuanxin.wqxuetang.com/page/img/
> 这个地址改成了
> https://lib-nuanxin.wqxuetang.com/page/lmg/
> ，可能Jwt的算法也有调整吧。

jwt的payload参数没有调整，wq那边增加了阿里人机验证（无痕验证）

**Comment by SweetInk** [comment]
请下载最新版使用
