### ISSUE TITLE
 加载授权url失败:CANCELLED

### ISSUE THREAD

**Issue by brave688** [SweetInk/wqxuetang-pdf-downloader#17]
![image](https://user-images.githubusercontent.com/20045733/74109390-f20c0e80-4bbd-11ea-8560-4de1a085dbdc.png)
直接下载relese的压缩包可执行，但是一直报这个错误，用浏览器访问http://127.0.0.1/nvc可以看到网页，点击register也能成功，但是就一直停着不动，只能强行中断。
另外源码编译后无法运行成功，可能是把App.java改名Main.java做的新版，源码也没有更新好，强行改pom.xml，结果运行也是报错。
![image](https://user-images.githubusercontent.com/20045733/74109497-e240fa00-4bbe-11ea-98c7-1712b37ba0bd.png)

**Comment by DiamondHunters** [comment]
源码未更新 
Latest release报错
[INFO ] 2020-02-10 04:52:26 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[ERROR] 2020-02-10 04:52:28 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

**Comment by SweetInk** [comment]
Duplicate of #20

**Comment by SweetInk** [comment]
> ![image](https://user-images.githubusercontent.com/20045733/74109390-f20c0e80-4bbd-11ea-8560-4de1a085dbdc.png)
> 直接下载relese的压缩包可执行，但是一直报这个错误，用浏览器访问[http://127.0.0.1/nvc可以看到网页，点击register也能成功，但是就一直停着不动，只能强行中断。](http://127.0.0.1/nvc%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E7%BD%91%E9%A1%B5%EF%BC%8C%E7%82%B9%E5%87%BBregister%E4%B9%9F%E8%83%BD%E6%88%90%E5%8A%9F%EF%BC%8C%E4%BD%86%E6%98%AF%E5%B0%B1%E4%B8%80%E7%9B%B4%E5%81%9C%E7%9D%80%E4%B8%8D%E5%8A%A8%EF%BC%8C%E5%8F%AA%E8%83%BD%E5%BC%BA%E8%A1%8C%E4%B8%AD%E6%96%AD%E3%80%82)
> 另外源码编译后无法运行成功，可能是把App.java改名Main.java做的新版，源码也没有更新好，强行改pom.xml，结果运行也是报错。
> ![image](https://user-images.githubusercontent.com/20045733/74109497-e240fa00-4bbe-11ea-98c7-1712b37ba0bd.png)

试下最新版
