### ISSUE TITLE
总页数获取错误

### ISSUE THREAD

**Issue by xyyhhh** [SweetInk/wqxuetang-pdf-downloader#18]
![image](https://user-images.githubusercontent.com/37466317/74112824-a451cf00-4bda-11ea-8a75-a31d3fdc1527.png)
书号3208473 总页数483

谢谢作者！

**Comment by xyyhhh** [comment]
而且每次获取的总页数还会不一样

**Comment by xyyhhh** [comment]
不影响实际使用

**Comment by SweetInk** [comment]
页数问题是因为程序会跳过已下载的部分
