### ISSUE TITLE
最终合成pdf时内容为空

### ISSUE THREAD

**Issue by fishheadsam** [SweetInk/wqxuetang-pdf-downloader#2]
同时下载的图片也都格式错误

**Comment by SweetInk** [comment]
截个图看看？

**Comment by fishheadsam** [comment]
![2020-02-05 12-32-53屏幕截图](https://user-images.githubusercontent.com/24820246/73842026-b535c580-4813-11ea-8f56-38bd27647e89.png)
![2020-02-05 12-47-50屏幕截图](https://user-images.githubusercontent.com/24820246/73843054-c089f080-4815-11ea-8e3b-949c07eed6c4.png)
现在连pdf都没了。。。

**Comment by SweetInk** [comment]
拉取最新代码，或者到release下载构建好的jar
