### ISSUE TITLE
online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

### ISSUE THREAD

**Issue by aniuyin** [SweetInk/wqxuetang-pdf-downloader#20]
[INFO ] 2020-02-10 13:39:38 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[ERROR] 2020-02-10 13:39:39 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

更新最新版本Release1.04 还是没用，求解~

**Comment by SweetInk** [comment]
电脑系统是啥?

**Comment by aniuyin** [comment]
win10,之前一直有用的，就是这次更新之后就这样了

**Comment by SweetInk** [comment]
> win10,之前一直有用的，就是这次更新之后就这样了

试下`1.0.5`,然后看下日志，我这里没法复现你的这个问题。程序启动后，顺便访问下[http://localhost:8081/nvc](http://localhost:8081/nvc)

**Comment by brave688** [comment]
win10，本地网站可访问，但无法进行下去，日志信息：
[INFO ] 2020-02-10 15:01:59 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[INFO ] 2020-02-10 15:02:00 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - oldState:RUNNING -> newState:CANCELLED
[ERROR] 2020-02-10 15:02:00 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

**Comment by aniuyin** [comment]
我看到有几位朋友也是问了这类问题，看来不是个例啊。

**Comment by aniuyin** [comment]
http://localhost:8081/nvc  
显示
Hello,world

**Comment by aniuyin** [comment]
[INFO ] 2020-02-10 15:08:31 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[ERROR] 2020-02-10 15:08:32 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

**Comment by SweetInk** [comment]
> [INFO ] 2020-02-10 15:08:31 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
> [ERROR] 2020-02-10 15:08:32 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

你的QQ多少，方便的话把你qq发到我[邮箱](mailto:suchu01@hotmail.com)里，我加你，然后给你单独测试。

**Comment by kiualen** [comment]
> > [INFO ] 2020-02-10 15:08:31 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
> > [ERROR] 2020-02-10 15:08:32 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED
> 
> 你的QQ多少，方便的话把你qq发到我[邮箱](mailto:suchu01@hotmail.com)里，我加你，然后给你单独测试。

一样授权失败

**Comment by eagle11235** [comment]
> > [INFO ] 2020-02-10 15:08:31 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
> > [ERROR] 2020-02-10 15:08:32 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED
> 
> 你的QQ多少，方便的话把你qq发到我[邮箱](mailto:suchu01@hotmail.com)里，我加你，然后给你单独测试。

同样的问题，授权失败

**Comment by wyap-echo** [comment]
同样的错误呀 
[INFO ] 2020-02-10 17:37:41 [main] online.githuboy.wqxuetang.pdfd.Main - Start internal http server success,Listen on port:8081
[INFO ] 2020-02-10 17:37:41 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - oldState:RUNNING -> newState:CANCELLED
[ERROR] 2020-02-10 17:37:41 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

**Comment by nilaoda** [comment]
同样错误

**Comment by qs9515** [comment]
online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

这个问题可能是因为JDK的原因，我win10之前也报这个错，换了一个jdk有jre的，官网下载的：
jdk-8u241-windows-x64.exe，改了环境变量地址，目前可以正常使用了。

**Comment by aniuyin** [comment]
@SweetInk  下载U241JAVA 已可以了，估计之前是老版本的JAVA，你开发新版本之后不支持了

**Comment by aniuyin** [comment]
但下载下来的都是8字节的文件图？啥都没？有谁和我一样？

**Comment by brave688** [comment]
@SweetInk 同样升级到241后可以正常使用。
