### ISSUE TITLE
[ERROR] 2020-02-10 19:06:35 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED

### ISSUE THREAD

**Issue by odd2008** [SweetInk/wqxuetang-pdf-downloader#22]
在mac上面
可以访问到http://localhost:8081/nvc
但报如下错误:

`ERROR] 2020-02-10 19:06:35 [JavaFX Application Thread] online.githuboy.wqxuetang.pdfd.ui.WebContainer - 加载授权url失败:CANCELLED`

**Comment by SweetInk** [comment]
Duplicate of #20
