### ISSUE TITLE
授权失败问题解决了，但下载的都是8字节的图？有谁和我一样的？

### ISSUE THREAD

**Issue by aniuyin** [SweetInk/wqxuetang-pdf-downloader#23]
授权失败问题解决了，但下载的都是8字节的图？有谁和我一样的？

**Comment by qs9515** [comment]
账号被禁止了

**Comment by aniuyin** [comment]
我擦，今天我都没下 就禁止了？

**Comment by xinpo66** [comment]
我都也是啊

**Comment by meininghang** [comment]
+1，我记得前两天就出现过这种图片不能使用的问题。

**Comment by xinpo66** [comment]
换个账号试试

**Comment by kiualen** [comment]
> 账号被禁止了

你可以正常下载？

**Comment by SweetInk** [comment]
账号被禁止了吧，话说这wq官网真够`狠`的，加了`阿里无痕验证`，又搞`用户请求限流`，双管齐下！

**Comment by qs9515** [comment]
> > 账号被禁止了
> 
> 你可以正常下载？

不可以，需要重新注册账号，没有弄了。

**Comment by kiualen** [comment]
> 账号被禁止了吧，话说这wq官网真够`狠`的，加了`阿里无痕验证`，又搞`用户请求限流`，双管齐下！

是请求速度过快，导致账号被禁止了吧，😄

**Comment by sheep111** [comment]
之前用油猴的没被封过号，这个刚配置好sleeptime都写了6秒了，下了15页直接被封号，明天重新注册继续。。。
