### ISSUE TITLE
请求NVC出错 bookId:XXX,pageNumber:XXX,volumeNumber:null, code:6001,msg:验证失败

### ISSUE THREAD

**Issue by bdrpc** [SweetInk/wqxuetang-pdf-downloader#24]
昨晚11点还可以用，刚pull最新版本，新验证上线？

**Comment by bdrpc** [comment]
可以继续用，浏览器开发者模式里可以看到几乎每页都有2个nvc，1个出错，1个正常。跳到大页码开始下载（或者说继续下载），得到的图都不对。

**Comment by weenhall** [comment]
用不了吧，一直验证失败，应该是打补丁了

**Comment by lovexuanqi521** [comment]
出现了个滑动验证,NVC验证失败

**Comment by bdrpc** [comment]
嗯，滑动验证。出错之后刷网页，人工都过不了现在的滑动验证。估计是限制访问了，重启新的任务，一般到第3页就不行了（没对比过cookies的变化，猜的）。

**Comment by xiaofan1991** [comment]
一样的报错

**Comment by SweetInk** [comment]
那边的程序员把NVC的验证URL改了🤣

**Comment by weenhall** [comment]
看到了v1,这是要捉迷藏啊，明天估计v2了

**Comment by SweetInk** [comment]
> 看到了v1,这是要捉迷藏啊，明天估计v2了

我账号被ban掉了，现在下载的全是8byte图片，你可以拉取最新代码测试下

**Comment by weenhall** [comment]
> > 看到了v1,这是要捉迷藏啊，明天估计v2了
> 
> 我账号被ban掉了，现在下载的全是8byte图片，你可以拉取最新代码测试下

现在加了滑块验证，得多下载几次

**Comment by SweetInk** [comment]
> 现在加了滑块验证，得多下载几次

滑块验证时无痕验证未通过时出现的。


trans字段值 | 模拟效果
-- | --
{“nvcCode”:200} | 无痕验证通过。
{“nvcCode”:400, “key1”: “code0”} | 唤醒滑动验证，且滑动验证通过。
{“nvcCode”:400, “key1”: “code300”} | 唤醒滑动验证，且滑动验证未通过（拦截）。
{“nvcCode”:600, “key1”: “code0”} | 唤醒刮刮卡验证，且刮刮卡验证通过。
{“nvcCode”:600, “key1”: “code300”} | 唤醒刮刮卡验证，且刮刮卡验证未通过（拦截）。
{“nvcCode”:700} | 唤醒问答验证。说明：由于问答验证码组件升级中，服务端暂时不会返回code为700的结果。
{“nvcCode”:800} | 无痕验证未通过，直接拦截。

**Comment by weenhall** [comment]
> > 现在加了滑块验证，得多下载几次
> 
> 滑块验证时无痕验证未通过时出现的。
> 
> trans字段值	模拟效果
> {“nvcCode”:200}	无痕验证通过。
> {“nvcCode”:400, “key1”: “code0”}	唤醒滑动验证，且滑动验证通过。
> {“nvcCode”:400, “key1”: “code300”}	唤醒滑动验证，且滑动验证未通过（拦截）。
> {“nvcCode”:600, “key1”: “code0”}	唤醒刮刮卡验证，且刮刮卡验证通过。
> {“nvcCode”:600, “key1”: “code300”}	唤醒刮刮卡验证，且刮刮卡验证未通过（拦截）。
> {“nvcCode”:700}	唤醒问答验证。说明：由于问答验证码组件升级中，服务端暂时不会返回code为700的结果。
> {“nvcCode”:800}	无痕验证未通过，直接拦截。

可以把阈值设置小点，估计对方对请求次数有限制，太快了就会出现，我现在设置每次下载5页比较稳定

**Comment by lovexuanqi521** [comment]
@weenhall 阈值怎么设，在哪个文件设，麻烦教一下！

**Comment by weenhall** [comment]
> @weenhall 阈值怎么设，在哪个文件设，麻烦教一下！

配置文件config.maxRequestThreshold=2
我还把间隔下载的时间设置成了随机数，这样比较稳定
FetchBookImageTask，找到这段代码，改成这样
>  if (AppContext.counter.get() >= AppContext.getConfig().getMaxRequestThreshold()) {
                Random random=new Random();
                int waitingSeconds=random.nextInt(12)+10;
                log.info("休眠{}秒再试", waitingSeconds);
                TimeUnit.SECONDS.sleep(waitingSeconds);
                log.info("任务继续执行");
                AppContext.counter.set(0);
            }

**Comment by lovexuanqi521** [comment]
@weenhall  程序中int 是啥意思？

**Comment by weenhall** [comment]
> @weenhall 程序中int 是啥意思？

数字一般有整型，浮点型等，这个代表整型，这里生成了一个随机数决定下一次下载的间隔时间

**Comment by lovexuanqi521** [comment]
我感觉账号被锁了，下载失败，都是8k图

**Comment by weenhall** [comment]
> 我感觉账号被锁了，下载失败，都是8k图

你用之前的默认的阈值45，太快了，可能这个被封，我每次只下载两张图片，稳稳地

**Comment by lovexuanqi521** [comment]
passid被锁了，身份验证失败的，有解吗？

**Comment by lovexuanqi521** [comment]
passid被锁了，身份验证失败的，有解吗？

**Comment by lovexuanqi521** [comment]
passid被锁了，身份验证失败的，有解吗？

**Comment by SweetInk** [comment]
> @weenhall 阈值怎么设，在哪个文件设，麻烦教一下！

`config.properties`中，文件有注释
