### ISSUE TITLE
每15分钟就会出错，下载的图片无效，大小为:10400 byte

### ISSUE THREAD

**Issue by kk930604** [SweetInk/wqxuetang-pdf-downloader#27]
每15分钟就无法下载，必须程序关掉等一会儿重新开才可以
[INFO ] 2020-02-11 22:54:07 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - Page:43 下载的图片无效，大小为:10400 byte
[INFO ] 2020-02-11 22:54:07 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - page:43 图片获取进行第:1 次重试
[INFO ] 2020-02-11 22:54:33 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - Page:44 下载的图片无效，大小为:10400 byte
[INFO ] 2020-02-11 22:54:48 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - page:44 图片获取进行第:1 次重试

**Comment by SweetInk** [comment]
等待一段时间下载，服务器限流了
