### ISSUE TITLE
NVC 验证失败

### ISSUE THREAD

**Issue by meininghang** [SweetInk/wqxuetang-pdf-downloader#28]
信息如下：
> [INFO ] 2020-02-12 12:22:48 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - page:13 图片获取进行第:1 次重试
[INFO ] 2020-02-12 12:22:57 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - NVC验证失败 bookId:4890,pageNumber:14,volumeNumber:null,result:{"RequestId":"400","BizCode":"400"}

**Comment by leedoll** [comment]
刷新网页出现 “身份验证失败，请刷新或重新登录后重试”，被封号了？

**Comment by kk930604** [comment]
> 信息如下：
> 
> > [INFO ] 2020-02-12 12:22:48 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - page:13 图片获取进行第:1 次重试
> > [INFO ] 2020-02-12 12:22:57 [fetch-image1-thread-1] online.githuboy.wqxuetang.pdfd.FetchBookImageTask - NVC验证失败 bookId:4890,pageNumber:14,volumeNumber:null,result:{"RequestId":"400","BizCode":"400"}

我也是这样，一旦出现这个，就是封号，要重新申请了，刷新网页出现 “身份验证失败，请刷新或重新登录后重试”，被封号了？

**Comment by sheep111** [comment]
是封号了，但是封的也太快了吧
间隔时间已经调到6秒了
第一个号下了15页被封
第二个号才下8页又被封

**Comment by EricChin2012** [comment]
> 是封号了，但是封的也太快了吧
> 间隔时间已经调到6秒了
> 第一个号下了15页被封
> 第二个号才下8页又被封

我下了4页，封得太快了。好奇是怎么判断出来的。header的内容？
