### ISSUE TITLE
线程数是否有必要调小一些，页数较多的文件很容易下载失败

### ISSUE THREAD

**Issue by jinstory** [SweetInk/wqxuetang-pdf-downloader#8]
一般超过300页的图书后面就很容易是空白的

**Comment by brave688** [comment]
线程过多也容易被判断成网络攻击。目前是根据cpu的核心数再乘以2，建议做成参数，或限制为4以下。

**Comment by jinstory** [comment]
> 线程过多也容易被判断成网络攻击。目前是根据cpu的核心数再乘以2，建议做成参数，或限制为4以下。

对于页数多的书应该下载150页后暂停几分钟然后继续下载可能没这么容易触发

**Comment by SweetInk** [comment]
> > 线程过多也容易被判断成网络攻击。目前是根据cpu的核心数再乘以2，建议做成参数，或限制为4以下。
> 
> 对于页数多的书应该下载150页后暂停几分钟然后继续下载可能没这么容易触发

搞成单线程试试😂

**Comment by SweetInk** [comment]
使用最新版本，在`config.properties`中配置`线程`等参数
