### ISSUE TITLE
获取失败，提示 Unexpected end of file from server

### ISSUE THREAD

**Issue by Becods** [SweetInk/wqxuetang-pdf-downloader#9]
RT
![bluer_02-06_15-51-55.png](https://i.loli.net/2020/02/06/gCWIp9oZvLV2JRB.png)

**Comment by SweetInk** [comment]
服务器没有返回任何内容，估计是文泉那边针对频繁请求的IP做了限制😒

**Comment by Becods** [comment]
更换代理测试，问题依旧

**Comment by SweetInk** [comment]
测试了下，这个限制应该和ip无关，应该和cookie中的用户信息有关，同一用户针对pdf书的图片请求做了限流

**Comment by Becods** [comment]
刚刚测试了下，账号和IP限制应该都有，换账号后8线程获取，大约200张后就无返回
更换IP后使用同账号，问题依旧
故希望能够增加获取一定数量后暂停一段时间再进行获取

**Comment by SweetInk** [comment]
得找到服务端允许的最大连续请求数阈值才行

**Comment by brave688** [comment]
昨天20点到23点间，3个线程大约70多张后就不行了，换成单线程也如此。需要等几十分钟才可以（没有具体看多久），然后也只能下70多张。现在基本下不到正确的图像了。

**Comment by Becods** [comment]
经过3小时测试，使用[15f6184](https://github.com/SweetInk/wqxuetang-pdf-downloader/commit/15f6184abd917c1f8f11c29ab674e7d12c7401fa)并调至比正常阅读速度还慢后再无发生此类错误（我有服务器，慢慢下）

**Comment by SweetInk** [comment]
> 经过3小时测试，使用[15f6184](https://github.com/SweetInk/wqxuetang-pdf-downloader/commit/15f6184abd917c1f8f11c29ab674e7d12c7401fa)并调至比正常阅读速度还慢后再无发生此类错误（我有服务器，慢慢下）

你的参数是多少?我看下。

**Comment by Becods** [comment]
> > 经过3小时测试，使用[15f6184](https://github.com/SweetInk/wqxuetang-pdf-downloader/commit/15f6184abd917c1f8f11c29ab674e7d12c7401fa)并调至比正常阅读速度还慢后再无发生此类错误（我有服务器，慢慢下）
> 
> 你的参数是多少?我看下。

阈值30，停顿120，休眠10000

**Comment by Becods** [comment]
~~好吧还是被封了
可能是因为新号限制不大
号越老，限制越严格~~
**原来是cookie过期了**
更新cookie后可以再进行获取
等我测试过期时间再来更新

**Comment by SweetInk** [comment]
> 好吧还是被封了
> 可能是因为新号限制不大
> 号越老，限制越严格

封的次数越多，后续请求限制就越大，正常阅读都受影响了

**Comment by Becods** [comment]
刚刚测试到cookie超时应该是15分钟
~~更新cookie后可继续获取~~
~~更新cookie后获取两张又被封了~~
~~不过此时在网页浏览是没问题的~~
等待5分钟测试又可以继续下载了

**Comment by brave688** [comment]
单线程，阈值50，停顿15，休眠8000，不贪心的话，基本不会出这个错误。但是时不时跳”图片错误65"，接着就是重试，但是肯定重试不成功。此时中断程序，重启即可继续下载。所以我在FetchBookImageTask.java 69行开始插入了一个计数器，超过两次图片错误我就野蛮中断，给个退出码。这样结合批处理文件，就可以无人值守了。可能大神有高级的解决方法，可是我不会java，只能这样处理了。

**Comment by meininghang** [comment]
已经调低到不贪心的程度，程序可以正常运行并不会报错，但是下载的图片是损坏的，无法预览、使用和合并。

**Comment by brave688** [comment]
> 已经调低到不贪心的程度，程序可以正常运行并不会报错，但是下载的图片是损坏的，无法预览、使用和合并。

我刚才也碰到了，不知是什么限制。

**Comment by SweetInk** [comment]
我调试看下

**Comment by brave688** [comment]
目前是高度怀疑凌晨2点多开始有了限制，返回的都是无效结果，即使用浏览器也是无法加载图片，换用户，用手机热点均无效，上午再看就恢复正常。我从11点开始到现在18点，无值守下了7本书，全部正常。反正这个速度，到16号也能下不少书吧，够好一阵看了，人不可贪心。
